ALTER TABLE "GeneralConfig" ADD COLUMN "qrBankCode" TEXT NOT NULL DEFAULT 'ICB';
ALTER TABLE "GeneralConfig" ADD COLUMN "qrAccountNumber" TEXT NOT NULL DEFAULT '11415686';
ALTER TABLE "GeneralConfig" ADD COLUMN "qrAccountName" TEXT NOT NULL DEFAULT 'HO KINH DOANH SAI GON AN COFFEE';
